# encoding:utf-8
activities = [
	{"code": u"1", "name": u"Jornales"},
	{"code": u"2", "name": u"Celaduria porteria"},
	{"code": u"3", "name": u"Fertilización Manual"},
	{"code": u"4", "name": u"Fertilización con voleadora"},
	{"code": u"5", "name": u"Transporte de fertilizalante"},
	{"code": u"6", "name": u"Fertilización borax"},
	{"code": u"7", "name": u"Mezcla Fertilizante"},
	{"code": u"8", "name": u"Cargue fertilizante"},
	{"code": u"9", "name": u"Ayudante Fertilización"},
	{"code": u"10", "name": u"Tractorista Fertilización"},
	{"code": u"11", "name": u"Limpieza piscina de oxidación"},
	{"code": u"12", "name": u"Jornal Planta Extractora"},
	{"code": u"13", "name": u"Jornal lavada de Tanques"},
	{"code": u"14", "name": u"Plateo con guadaña"},
	{"code": u"15", "name": u"Plateo Químico"},
	{"code": u"16", "name": u"Limpieza de platos (Rastrilla}"},
	{"code": u"17", "name": u"Guachapeo (Rocería}"},
	{"code": u"18", "name": u"Roceria manual de canales principales"},
	{"code": u"19", "name": u"Roceria manual de canales secundarios"},
	{"code": u"20", "name": u"Control de malezas con Rotospeed"},
	{"code": u"21", "name": u"Control de malezas con rolo"},
	{"code": u"22", "name": u"Control de malezas con palo"},
	{"code": u"23", "name": u"Jornal de riego"},
	{"code": u"24", "name": u"Poda 7 meses"},
	{"code": u"25", "name": u"Poda 8 meses"},
	{"code": u"26", "name": u"Poda 9 meses"},
	{"code": u"27", "name": u"Poda 10 meses"},
	{"code": u"28", "name": u"Poda 11 meses"},
	{"code": u"29", "name": u"Poda 12 meses"},
	{"code": u"30", "name": u"Hora retroexcavadora"},
	{"code": u"31", "name": u"Hora guadaña"},
	{"code": u"32", "name": u"Siembra mucuna - KUDZU"},
	{"code": u"33", "name": u"Plateo con guadaña todo costo"},
	{"code": u"34", "name": u"Plateo con Herbis"},
	{"code": u"35", "name": u"Poda Ranchones"},
	{"code": u"36", "name": u"Jornal Bocatoma"},
	{"code": u"37", "name": u"Envagonetado"},
	{"code": u"38", "name": u"Aceite Producido"},
	{"code": u"39", "name": u"Almendra Producida"},
	{"code": u"40", "name": u"Cargue de Almendra"},
	{"code": u"41", "name": u"Descargue torta palmiste"},
	{"code": u"42", "name": u"Manejo caldera para calentamiento de aceite y almendra"},
	{"code": u"43", "name": u"Proceso nuez"},
	{"code": u"44", "name": u"Lavada Lonas"},
	{"code": u"45", "name": u"Corte de fruta"},
	{"code": u"46", "name": u"Recolección fruto"},
	{"code": u"47", "name": u"Cargue de fruto"},
	{"code": u"48", "name": u"Descargue de fruto"},
	{"code": u"49", "name": u"Transporte de fruto"},
	{"code": u"50", "name": u"Transporte de tusa, impurezas, fibra y otros"},
	{"code": u"51", "name": u"Cargue y descargue otros"},
	{"code": u"52", "name": u"Horas tractor"},
	{"code": u"53", "name": u"Cargue de fruto con retroescavadora"},
	{"code": u"54", "name": u"Repepeo"},
	{"code": u"55", "name": u"Horas tractor Palmallanito y Plantaciónes"},
	{"code": u"56", "name": u"Cargue fruto Palmallanito y Plantaciónes"},
	{"code": u"57", "name": u"Descargue fruto Palmallanito y Plantaciónes"},
	{"code": u"58", "name": u"Cuidado animales"},
	{"code": u"59", "name": u"Peso promedio lote tractorista"},
	{"code": u"60", "name": u"Peso promedio lote carguero"},
	{"code": u"61", "name": u"Corte fruta Palmallanito"},
	{"code": u"62", "name": u"Recolección fruta Palmallanito"},
	{"code": u"63", "name": u"Transporte fruto otras plantaciónes"},
	{"code": u"64", "name": u"Recolección adultos Cyparissius"},
	{"code": u"65", "name": u"Aplicación insecticidas con bomba espalda Focos ML"},
	{"code": u"66", "name": u"Aplicación mezcla para PC"},
	{"code": u"67", "name": u"Poda palma ML"},
	{"code": u"68", "name": u"Desinfección herramienta"},
	{"code": u"69", "name": u"Control de stomoxys lote"},
	{"code": u"70", "name": u"Tratamiento inyección de palmas"},
	{"code": u"71", "name": u"Control de stmoxys perimetral"},
	{"code": u"72", "name": u"Control hormigas"},
	{"code": u"73", "name": u"Cirugia PC"},
	{"code": u"74", "name": u"Control y monitoreo trampas rynchophorus"},
	{"code": u"75", "name": u"Recirugia PC"},
	{"code": u"76", "name": u"Censo enfermedades letales otras plantaciónes"},
	{"code": u"77", "name": u"Control de stmoxys lote otras plantaciónes"},
	{"code": u"78", "name": u"Nomenclatura marcación"},
	{"code": u"79", "name": u"Jornal fumigación JACTO"},
	{"code": u"80", "name": u"Siembra de palma"},
	{"code": u"81", "name": u"Cargue y descargue palma"},
]
def charge_data():
	from apps.process_admin.models import Activities
	from django.contrib.auth.models import User
	activities_list = []
	u = User.objects.get(id=1)
	for a in activities:
		activities_list.append(Activities(value="0", user=u, **a))
	Activities.objects.bulk_create(activities_list)